# Generated by Django 5.2 on 2025-04-26 18:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountio", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vendoruser",
            unique_together={("user", "vendor")},
        ),
    ]
