# Generated by Django 5.2 on 2025-04-27 09:45

import dirtyfields.dirtyfields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True)),
                ("order_id", models.CharField(blank=True, max_length=50)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ORDER_PLACED", "Order Placed"),
                            ("PROCESSING", "Processing"),
                            ("PAYMENT_INCOMPLETE", "Payment Incomplete"),
                            ("ON_THE_WAY", "On the way"),
                            ("OUT_FOR_DELIVERY", "Out for delivery"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="PAYMENT_INCOMPLETE",
                        max_length=50,
                    ),
                ),
                ("is_ordered", models.BooleanField(default=False)),
                ("is_paid", models.BooleanField(default=False)),
                ("address", models.CharField(blank=True, max_length=1000)),
                (
                    "order_shipping_charge",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True)),
                ("quantity", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "total_product_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orderio.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productio.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                blank=True, through="orderio.OrderItems", to="productio.product"
            ),
        ),
    ]
